name = "dracinku"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "API_CONFIG"
id = "628f407be7194841861f526e3a421ec0"
